# Generated by Django 3.2.4 on 2021-07-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_remove_todo_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='todo_text',
            field=models.CharField(max_length=1000, null=True, verbose_name=''),
        ),
    ]
