# Generated by Django 3.2.4 on 2021-07-22 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_alter_todo_todo_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='todo_text',
        ),
        migrations.AddField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=1000, null=True, verbose_name=''),
        ),
    ]
